print("student details")
name=input("name:")
age=int(input("age:"))
college=input("college:")
department=input("department:")
print("name:",name)
print("age:  ",age)
print("college:",college)
print("department:",department)
